<?php

declare(strict_types=1);

namespace Mailyte\EmailTemplates\Adoption;

use Mailyte\EmailTemplates\Themes\Theme;

/**
 * Restyles Laravel's markdown mailables from a Mailyte design.
 *
 * Markdown mailables are a different mechanism from notifications: they render
 * through Laravel's `mail::` Blade components and are styled by a single CSS
 * file, looked up as a view (`css` is a registered view extension resolved by
 * the file engine). So the way to restyle every markdown mailable in an
 * application without touching any of them is to write that file.
 *
 * This is a translation, not a rewrite. Laravel's components have their own
 * markup and their own class names, so what comes out is Laravel's structure
 * wearing a Mailyte design: same palette, type scale, fonts, radii and rhythm.
 * It will not be pixel-identical to a real Mailyte template -- the blocks are
 * not there -- and pretending otherwise would be dishonest. It does mean an
 * application's markdown mail stops looking like the framework default.
 */
class MarkdownThemeCompiler
{
    public function compile(Theme $theme, string $sourceSlug = ''): string
    {
        $t = fn (string $path, string $fallback = ''): string => (string) ($theme->get($path, $fallback) ?: $fallback);

        $bg = $t('color.bg', '#F2F4F6');
        $surface = $t('color.surface', '#FFFFFF');
        $surfaceAlt = $t('color.surface_alt', '#F7F8FA');
        $ink = $t('color.text', '#1F2933');
        $muted = $t('color.text_muted', '#6B7280');
        $border = $t('color.border', '#E4E7EB');
        $primary = $t('color.primary', '#2C64E3');
        $primaryInk = $t('color.primary_text', '#FFFFFF');
        $danger = $t('color.danger', $t('color.primary', '#BF2C2C'));
        $success = $t('color.success', $primary);
        $link = $t('color.link', $primary);

        $bodyFont = $t('font.body', "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif");
        $headingFont = $t('font.heading', $bodyFont);

        $bodySize = $t('type.body.size', '16px');
        $bodyLine = $t('type.body.line_height', '26px');
        $h1Size = $t('type.h1.size', '24px');
        $h1Line = $t('type.h1.line_height', '32px');
        $h1Weight = $t('type.h1.weight', '600');
        $h2Size = $t('type.h2.size', '19px');
        $smallSize = $t('type.small.size', '13px');
        $smallLine = $t('type.small.line_height', '21px');
        $buttonSize = $t('type.button.size', '15px');
        $buttonWeight = $t('type.button.weight', '600');

        $radiusMd = $t('radius.md', '6px');
        $radiusLg = $t('radius.lg', '10px');
        $width = $t('layout.width', '600px');
        $gutter = $t('layout.gutter', '36px');
        $outer = $t('layout.outer_padding', '36px');

        $origin = $sourceSlug === ''
            ? 'a Mailyte theme'
            : "the `{$sourceSlug}` template's design";

        return <<<CSS
/* Generated by `php artisan mailyte:adopt` from {$origin}.
 *
 * This styles Laravel's own markdown mailables -- the ones using `markdown:` in
 * a Mailable's content() -- so they stop looking like the framework default.
 * Regenerate it by running the command again; edits here are overwritten.
 *
 * Laravel's markup, Mailyte's design. For the real thing, convert the mailable
 * to a Mailyte template: see docs/laravel-integration.md.
 */

/* Base */

body {
    background-color: {$bg};
    color: {$ink};
    font-family: {$bodyFont};
    -webkit-text-size-adjust: none;
    margin: 0;
    padding: 0;
    width: 100% !important;
}

body *:not(html):not(style):not(br):not(tr):not(code) {
    font-family: {$bodyFont};
    box-sizing: border-box;
}

p {
    color: {$ink};
    font-size: {$bodySize};
    line-height: {$bodyLine};
    margin-top: 0;
    margin-bottom: 16px;
    text-align: left;
}

p.sub {
    color: {$muted};
    font-size: {$smallSize};
    line-height: {$smallLine};
}

h1 {
    color: {$ink};
    font-family: {$headingFont};
    font-size: {$h1Size};
    line-height: {$h1Line};
    font-weight: {$h1Weight};
    margin-top: 0;
    margin-bottom: 18px;
    text-align: left;
}

h2 {
    color: {$ink};
    font-family: {$headingFont};
    font-size: {$h2Size};
    font-weight: {$h1Weight};
    margin-top: 0;
    margin-bottom: 12px;
    text-align: left;
}

h3 {
    color: {$ink};
    font-family: {$headingFont};
    font-size: {$bodySize};
    font-weight: 600;
    margin-top: 0;
    margin-bottom: 10px;
    text-align: left;
}

a {
    color: {$link};
    text-decoration: underline;
}

a img {
    border: none;
}

img {
    max-width: 100%;
    border: none;
}

blockquote {
    border-left: 3px solid {$border};
    margin: 0 0 18px;
    padding-left: 18px;
    color: {$muted};
}

/* Layout */

.wrapper {
    background-color: {$bg};
    margin: 0;
    padding: 0;
    width: 100%;
    -premailer-cellpadding: 0;
    -premailer-cellspacing: 0;
}

.content {
    margin: 0;
    padding: 0;
    width: 100%;
    -premailer-cellpadding: 0;
    -premailer-cellspacing: 0;
}

.header {
    padding: {$outer} 0 22px;
    text-align: center;
}

.header a {
    color: {$ink};
    font-family: {$headingFont};
    font-size: 19px;
    font-weight: 600;
    text-decoration: none;
}

.logo {
    height: 42px;
    max-height: 42px;
    width: auto;
}

.body {
    background-color: {$bg};
    border-bottom: 0;
    border-top: 0;
    margin: 0;
    padding: 0;
    width: 100%;
    -premailer-cellpadding: 0;
    -premailer-cellspacing: 0;
}

.inner-body {
    background-color: {$surface};
    border-radius: {$radiusLg};
    margin: 0 auto;
    padding: 0;
    width: {$width};
    -premailer-cellpadding: 0;
    -premailer-cellspacing: 0;
    -premailer-width: {$width};
}

.inner-body a {
    word-break: break-word;
}

.content-cell {
    max-width: 100vw;
    padding: {$gutter};
}

/* Button */

.action {
    margin: 26px auto;
    padding: 0;
    text-align: left;
    width: 100%;
    -premailer-cellpadding: 0;
    -premailer-cellspacing: 0;
    -premailer-width: 100%;
}

.button,
.inner-body a.button,
.action a.button {
    color: {$primaryInk};
}

.button {
    border-radius: {$radiusMd};
    color: {$primaryInk};
    display: inline-block;
    overflow: hidden;
    text-decoration: none;
    font-family: {$bodyFont};
    font-size: {$buttonSize};
    font-weight: {$buttonWeight};
    line-height: 1;
    padding: 15px 26px;
    -webkit-text-size-adjust: none;
}

.button-primary {
    background-color: {$primary};
    border-bottom: 8px solid {$primary};
    border-left: 18px solid {$primary};
    border-right: 18px solid {$primary};
    border-top: 8px solid {$primary};
}

.button-success {
    background-color: {$success};
    border-bottom: 8px solid {$success};
    border-left: 18px solid {$success};
    border-right: 18px solid {$success};
    border-top: 8px solid {$success};
}

.button-error {
    background-color: {$danger};
    border-bottom: 8px solid {$danger};
    border-left: 18px solid {$danger};
    border-right: 18px solid {$danger};
    border-top: 8px solid {$danger};
}

/* Panel and table */

.panel {
    border-left: 3px solid {$primary};
    margin: 22px 0;
}

.panel-content {
    background-color: {$surfaceAlt};
    color: {$ink};
    padding: 18px;
}

.panel-content p {
    color: {$ink};
}

.panel-item {
    padding: 0;
}

.panel-item p:last-of-type {
    margin-bottom: 0;
    padding-bottom: 0;
}

.table table {
    margin: 26px auto;
    width: 100%;
    -premailer-cellpadding: 0;
    -premailer-cellspacing: 0;
    -premailer-width: 100%;
}

.table th {
    border-bottom: 1px solid {$border};
    padding-bottom: 8px;
    margin: 0;
    color: {$muted};
    font-size: {$smallSize};
    text-align: left;
}

.table td {
    color: {$ink};
    font-size: {$bodySize};
    line-height: {$bodyLine};
    padding: 10px 0;
    margin: 0;
    border-bottom: 1px solid {$border};
}

/* Subcopy and footer */

.subcopy {
    border-top: 1px solid {$border};
    margin-top: 26px;
    padding-top: 18px;
}

.subcopy p {
    font-size: {$smallSize};
    line-height: {$smallLine};
    color: {$muted};
}

.footer {
    margin: 0 auto;
    padding: 0;
    text-align: center;
    width: {$width};
    -premailer-cellpadding: 0;
    -premailer-cellspacing: 0;
    -premailer-width: {$width};
}

.footer p {
    color: {$muted};
    font-size: 12px;
    line-height: 19px;
    text-align: center;
}

.footer a {
    color: {$muted};
    text-decoration: underline;
}

.break-all {
    word-break: break-all;
}

/* Dark mode, for the clients that honour it. Laravel's own theme has none. */

@media (prefers-color-scheme: dark) {
    body, .wrapper, .body {
        background-color: {$theme->get('color.bg', $bg, 'dark')} !important;
    }

    .inner-body, .panel-content {
        background-color: {$theme->get('color.surface', $surface, 'dark')} !important;
    }

    h1, h2, h3, p, .table td, .panel-content p {
        color: {$theme->get('color.text', $ink, 'dark')} !important;
    }

    p.sub, .subcopy p, .footer p, .footer a, .table th {
        color: {$theme->get('color.text_muted', $muted, 'dark')} !important;
    }

    a:not(.button), .inner-body a:not(.button), .header a {
        color: {$theme->get('color.link', $link, 'dark')} !important;
    }

    .button, .inner-body a.button {
        color: {$theme->get('color.primary_text', $primaryInk, 'dark')} !important;
    }

    .subcopy, .table th, .table td, blockquote {
        border-color: {$theme->get('color.border', $border, 'dark')} !important;
    }
}

CSS;
    }
}
