<?php

declare(strict_types=1);

namespace Mailyte\EmailTemplates\Console;

use Illuminate\Console\Command;
use Mailyte\EmailTemplates\Adoption\MarkdownThemeCompiler;
use Mailyte\EmailTemplates\MailyteManager;

class AdoptCommand extends Command
{
    protected $signature = 'mailyte:adopt
        {design? : A template whose design every Laravel email should take, e.g. email-changed}
        {--reset : Put Laravel back to its own mail rendering and remove what this command wrote}
        {--layout= : Force a layout for adopted mail: plain, minimal, branded or editorial}
        {--theme= : Force a base theme}
        {--no-markdown : Skip restyling Laravel markdown mailables}
        {--no-env : Do not touch .env; print the line to add instead}
        {--force : Overwrite files this command has written before}';

    protected $description = 'Make every email Laravel already sends use one Mailyte design';

    public function handle(MailyteManager $mailyte, MarkdownThemeCompiler $compiler): int
    {
        if ($this->option('reset')) {
            return $this->reset();
        }

        $slug = $this->argument('design');

        if (! is_string($slug) || $slug === '') {
            $slug = $this->askForDesign($mailyte);
        }

        $source = $mailyte->sources()->find($slug);

        if ($source === null) {
            $this->components->error("No template called [{$slug}]. Run `php artisan mailyte:list` to see what is available.");

            return self::FAILURE;
        }

        $this->components->info("Adopting the {$source->name()} design for every email Laravel sends.");
        $this->explainScope($slug);

        $steps = [
            fn (): bool => $this->publishShell($source->design(), $slug),
        ];

        if (! $this->option('no-markdown')) {
            $steps[] = fn (): bool => $this->writeMarkdownTheme($mailyte, $compiler, $slug);
        }

        $steps[] = fn (): bool => $this->enable();

        foreach ($steps as $step) {
            if (! $step()) {
                return self::FAILURE;
            }
        }

        $this->summary($slug);

        return self::SUCCESS;
    }

    /**
     * Hand Laravel its own mail rendering back.
     *
     * Turning the flag off is enough to restore Laravel's rendering on its own
     * -- the published files are simply not consulted. This also removes them,
     * so nothing is left behind wondering whether it is live. What it will not
     * do is delete work: a shell whose markup has been edited is kept unless
     * `--force` says otherwise, because that edit is somebody's afternoon.
     */
    private function reset(): int
    {
        $this->components->info('Handing mail rendering back to Laravel.');
        $this->newLine();

        $shell = rtrim((string) config('mailyte.sources.published'), '/').'/laravel-notification';
        $theme = resource_path('views/vendor/mail/html/themes/mailyte.css');
        $shipped = __DIR__.'/../../resources/shells/laravel-notification';

        if (! is_dir($shell)) {
            $this->components->twoColumnDetail('Notification shell', '<fg=gray>nothing published</>');
        } elseif ($this->wasEdited($shell, $shipped) && ! $this->option('force')) {
            $this->components->twoColumnDetail('Notification shell', '<fg=yellow>edited, kept</>');
            $this->line('  <fg=gray>'.$this->relative($shell).'</>');
            $this->line('  <fg=gray>It is inert with adoption off. Pass --force to delete it anyway.</>');
        } else {
            $this->deleteDirectory($shell);
            $this->components->twoColumnDetail('Notification shell', '<fg=green>removed</>');
        }

        if (! is_file($theme)) {
            $this->components->twoColumnDetail('Markdown mail theme', '<fg=gray>nothing written</>');
        } elseif (! str_contains((string) file_get_contents($theme), 'Generated by `php artisan mailyte:adopt`') && ! $this->option('force')) {
            // Someone replaced the generated file with their own. Not ours to delete.
            $this->components->twoColumnDetail('Markdown mail theme', '<fg=yellow>hand-edited, kept</>');
            $this->line('  <fg=gray>'.$this->relative($theme).'</>');
        } else {
            unlink($theme);
            $this->components->twoColumnDetail('Markdown mail theme', '<fg=green>removed</>');
        }

        $this->setEnv('false');

        $this->newLine();
        $this->components->info('Laravel is rendering its own mail again.');
        $this->line('  <fg=gray>Nothing else changed: your notification classes were never touched.</>');
        $this->newLine();

        return self::SUCCESS;
    }

    /**
     * Does the published shell still match what was shipped?
     */
    private function wasEdited(string $published, string $shipped): bool
    {
        // design.json is generated per adoption, so a difference there is
        // expected and says nothing about whether anyone edited anything.
        foreach (['email.html', 'template.json', 'sample.json'] as $file) {
            $a = is_file($published.'/'.$file) ? (string) file_get_contents($published.'/'.$file) : null;
            $b = is_file($shipped.'/'.$file) ? (string) file_get_contents($shipped.'/'.$file) : null;

            if ($a !== $b) {
                return true;
            }
        }

        return false;
    }

    private function deleteDirectory(string $dir): void
    {
        foreach ((array) glob($dir.'/*') as $path) {
            if (is_string($path) && is_file($path)) {
                unlink($path);
            }
        }

        if (is_dir($dir)) {
            rmdir($dir);
        }
    }

    private function askForDesign(MailyteManager $mailyte): string
    {
        $slugs = array_keys($mailyte->catalog());

        return (string) $this->choice(
            'Which template\'s design should every Laravel email use?',
            $slugs,
            in_array('notification', $slugs, true) ? 'notification' : ($slugs[0] ?? ''),
        );
    }

    /**
     * Say plainly what "use this design everywhere" can and cannot mean.
     */
    private function explainScope(string $slug): void
    {
        $this->newLine();
        $this->line("  <fg=gray>Laravel's own mail carries only a greeting, some lines and one action, so</>");
        $this->line("  <fg=gray>it cannot be rendered *through* {$slug} -- that template wants its own</>");
        $this->line('  <fg=gray>facts. What it can wear is that design: the palette, type scale, fonts,</>');
        $this->line('  <fg=gray>spacing and radii, applied to a shell that accepts any content.</>');
        $this->newLine();
    }

    /**
     * Copy the notification shell into the application, with the chosen
     * template's design tokens in place of the shell's own.
     *
     * @param  array<string, mixed>  $design
     */
    private function publishShell(array $design, string $slug): bool
    {
        $target = rtrim((string) config('mailyte.sources.published'), '/').'/laravel-notification';
        $shell = __DIR__.'/../../resources/shells/laravel-notification';

        if (is_dir($target) && ! $this->option('force')) {
            $this->components->twoColumnDetail('Notification shell', '<fg=yellow>already published, left alone</>');
            $this->line('  <fg=gray>Pass --force to replace it with the '.$slug.' design.</>');

            return true;
        }

        if (! is_dir($target) && ! mkdir($target, 0755, true) && ! is_dir($target)) {
            $this->components->error("Could not create {$target}");

            return false;
        }

        foreach (['template.json', 'email.html', 'sample.json'] as $file) {
            if (is_file($shell.'/'.$file)) {
                copy($shell.'/'.$file, $target.'/'.$file);
            }
        }

        // The design is the whole point of the command, so it is the one file
        // that does not come from the shell.
        file_put_contents(
            $target.'/design.json',
            json_encode(
                ['tokens' => $this->nest($design + $this->buttonStyle($slug))],
                JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES
            )."\n",
        );

        $this->components->twoColumnDetail('Notification shell', '<fg=green>published with the '.$slug.' design</>');
        $this->line('  <fg=gray>'.$this->relative($target).'</>');

        return true;
    }

    private function writeMarkdownTheme(MailyteManager $mailyte, MarkdownThemeCompiler $compiler, string $slug): bool
    {
        $dir = resource_path('views/vendor/mail/html/themes');

        if (! is_dir($dir) && ! mkdir($dir, 0755, true) && ! is_dir($dir)) {
            $this->components->error("Could not create {$dir}");

            return false;
        }

        $path = $dir.'/mailyte.css';

        if (is_file($path) && ! $this->option('force')) {
            $this->components->twoColumnDetail('Markdown mail theme', '<fg=yellow>already written, left alone</>');

            return true;
        }

        // Resolve through a real render so the CSS reflects the same precedence
        // a sent message gets: theme, then the design, then brand config.
        $theme = $mailyte->template($slug)->resolvedTheme();

        file_put_contents($path, $compiler->compile($theme, $slug));

        $this->components->twoColumnDetail('Markdown mail theme', '<fg=green>written from the '.$slug.' design</>');
        $this->line('  <fg=gray>'.$this->relative($path).'</>');

        return true;
    }

    private function enable(): bool
    {
        return $this->setEnv('true');
    }

    private function setEnv(string $value): bool
    {
        $line = 'MAILYTE_ADOPT_NOTIFICATIONS='.$value;

        if ($this->option('no-env')) {
            $this->components->twoColumnDetail('Environment', '<fg=yellow>not touched</>');
            $this->line("  <fg=gray>Add this yourself: {$line}</>");

            return true;
        }

        $path = base_path('.env');

        if (! is_file($path)) {
            $this->components->twoColumnDetail('Environment', '<fg=yellow>no .env found</>');
            $this->line("  <fg=gray>Add this yourself: {$line}</>");

            return true;
        }

        $contents = (string) file_get_contents($path);

        // Touch only this key. Everything else in the file is somebody's
        // credentials and is none of this command's business.
        if (preg_match('/^MAILYTE_ADOPT_NOTIFICATIONS=.*$/m', $contents) === 1) {
            $updated = (string) preg_replace('/^MAILYTE_ADOPT_NOTIFICATIONS=.*$/m', $line, $contents);
        } else {
            $updated = rtrim($contents, "\n")."\n\n".$line."\n";
        }

        if ($updated !== $contents) {
            file_put_contents($path, $updated);
        }

        $this->components->twoColumnDetail('Environment', "<fg=green>{$line}</>");

        return true;
    }

    private function summary(string $slug): void
    {
        $this->newLine();
        $this->components->info('Done. Every Laravel mail notification now wears the '.$slug.' design.');

        $this->line('  <options=bold>Covered</>');
        $this->line('  <fg=gray>·</> Laravel\'s password reset and email verification');
        $this->line('  <fg=gray>·</> Every notification of yours whose toMail() returns a MailMessage');
        $this->line('  <fg=gray>·</> Fortify, Jetstream and Breeze notifications');

        if (! $this->option('no-markdown')) {
            $this->line('  <fg=gray>·</> Markdown mailables, restyled through Laravel\'s own components');
        }

        $this->newLine();
        $this->line('  <options=bold>Left alone, deliberately</>');
        $this->line('  <fg=gray>·</> A MailMessage that chose its own view or markdown template');
        $this->line('  <fg=gray>·</> A toMail() returning a Mailable — that path is yours');
        $this->newLine();

        $this->brandHint();

        $this->newLine();
        $this->line('  <options=bold>Check it</>');
        $this->line('  <fg=gray>php artisan mailyte:send-test laravel-notification --to=you@example.com</>');
        $this->line('  <fg=gray>php artisan mailyte:deliverability laravel-notification</>');
        $this->newLine();
        $this->line('  <options=bold>Back out</>');
        $this->line('  <fg=gray>php artisan mailyte:adopt --reset</>');
        $this->newLine();
    }

    /**
     * A template's button shape and variant, which live in its markup rather
     * than in its design tokens.
     *
     * This is the one part of a design that `design.json` does not carry, and
     * it is too visible to drop: a pill button and a squared one read as
     * different designs, not as the same design in another colour. So the first
     * `button()` call in the source template is read and its shape and variant
     * are written into the adopted design as tokens the shell honours.
     *
     * `link` is deliberately not carried. It is a legitimate choice for a
     * secondary action inside a template that has a filled primary elsewhere,
     * but a notification has exactly one action, and turning it into bare text
     * would be a downgrade rather than a style.
     *
     * @return array<string, string>
     */
    private function buttonStyle(string $slug): array
    {
        $manifest = app(MailyteManager::class)->sources()->find($slug);

        if ($manifest === null || ! $manifest->has('email.html')) {
            return [];
        }

        preg_match_all('/\bbutton\s*\(\s*\{(.*?)\}\s*\)/s', $manifest->html(), $calls);

        foreach ($calls[1] as $props) {
            // A button carrying an explicit colour was tuned for one particular
            // band -- a dark masthead, an inset panel -- and is not the
            // template's ordinary treatment. Skip it and keep looking.
            if (preg_match('/\bcolor:/', $props) === 1) {
                continue;
            }

            $tokens = [];

            if (preg_match("/\bshape:\s*'(default|square|pill)'/", $props, $m) === 1) {
                $tokens['button.shape'] = $m[1];
            }

            if (preg_match("/\bvariant:\s*'(primary|secondary|outline)'/", $props, $m) === 1) {
                $tokens['button.variant'] = $m[1];
            }

            return $tokens;
        }

        // Every button in the template was context-specific, so there is no
        // house treatment to carry. The shell's filled primary is the safe
        // answer, not a guess.
        return [];
    }

    /**
     * A fresh application has no brand configured, so the design lands but the
     * chrome around it does not: no logo, no social row, no postal address.
     * Worth saying out loud, because the difference between "it worked" and "it
     * looks finished" is four lines of config.
     */
    private function brandHint(): void
    {
        $missing = [];

        if (! config('mailyte.brand.logo.url')) {
            $missing['MAILYTE_LOGO_URL'] = 'your mark, as an absolute https URL (add MAILYTE_LOGO_DARK_URL too)';
        }

        if (config('mailyte.brand.social', []) === []) {
            $missing["config('mailyte.brand.social')"] = 'the accounts to show in the footer';
        }

        if (! config('mailyte.brand.footer.address') && ! config('mailyte.globals.company.address')) {
            $missing['MAILYTE_COMPANY_ADDRESS'] = 'your postal address, which bulk mail is required to carry';
        }

        if ($missing === []) {
            return;
        }

        $this->newLine();
        $this->line('  <options=bold>Finish the look</>');
        $this->line('  <fg=gray>The design is in place. These are still unset, so the footer is bare:</>');

        foreach ($missing as $key => $what) {
            $this->line("  <fg=gray>·</> <fg=yellow>{$key}</> <fg=gray>— {$what}</>");
        }

        $this->line('  <fg=gray>Publish the config to edit it: php artisan vendor:publish --tag=mailyte-mail-config</>');
        $this->line('  <fg=gray>Social icons need hosting: php artisan vendor:publish --tag=mailyte-assets</>');
    }

    /**
     * Dot-path tokens back into the nested shape design.json is written in.
     *
     * @param  array<string, mixed>  $flat
     * @return array<string, mixed>
     */
    private function nest(array $flat): array
    {
        $out = [];

        foreach ($flat as $path => $value) {
            $keys = explode('.', (string) $path);
            $cursor = &$out;

            foreach ($keys as $i => $key) {
                if ($i === count($keys) - 1) {
                    $cursor[$key] = $value;

                    continue;
                }

                $cursor[$key] = is_array($cursor[$key] ?? null) ? $cursor[$key] : [];
                $cursor = &$cursor[$key];
            }

            unset($cursor);
        }

        return $out;
    }

    private function relative(string $path): string
    {
        return str_starts_with($path, base_path()) ? ltrim(substr($path, strlen(base_path())), '/') : $path;
    }
}
